In [7]:
import numpy as np

In [8]:
my_list=[11,2,3]

In [9]:
type(my_list)

list

In [10]:
np.array(my_list)

array([11,  2,  3])

In [11]:
myarr=np.array(my_list)

In [12]:
myarr

array([11,  2,  3])

In [13]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [14]:
my_mstrix

NameError: name 'my_mstrix' is not defined

In [15]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(8,int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((4,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.ones((5,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,100,15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.linespace(0,10,11)

AttributeError: module 'numpy' has no attribute 'linespace'

In [28]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
 np.random.rand(0,10)

array([], shape=(0, 10), dtype=float64)

In [44]:
np.random.rand(1)

array([0.55401702])

In [80]:
np.random.rand(2,2)

array([[0.52695592, 0.48989867],
       [0.1944901 , 0.37048417]])

In [81]:
np.randpm.rand(3)

AttributeError: module 'numpy' has no attribute 'randpm'

In [82]:
np.random.randn(2,3)

array([[-0.63971061,  0.5150874 , -0.46377602],
       [ 1.38578777,  1.73941516,  0.66052154]])

In [83]:
np.random.randint(1,40,4)

array([ 4, 39, 35, 35])

In [84]:
np.random.randint(1,40,(4,4))

array([[ 4, 33, 31, 25],
       [19, 16,  7, 26],
       [33, 14, 25,  3],
       [27, 21, 13, 27]])

In [94]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [100]:
np.random.seed(50)
np.random.rand(4)

array([0.49460165, 0.2280831 , 0.25547392, 0.39632991])

In [102]:
arr=np.arange(0,25)

In [103]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [104]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
ranarr=np.random.randint(0,101,10)

In [106]:
ranarr

array([70, 22,  5,  2, 95, 71, 68, 78, 35, 92])

In [107]:
ranarr.max

<function ndarray.max>

In [108]:
ranarr.max()

95

In [109]:
ranarr.min()

2

In [110]:
ranarr.sort()


In [111]:
ranarr

array([ 2,  5, 22, 35, 68, 70, 71, 78, 92, 95])

In [112]:
ranarr.argmin()

0

In [113]:
ranarr.shape()

TypeError: 'tuple' object is not callable

In [114]:
ranarr.shape

(10,)

In [115]:
arr.shape

(25,)